---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-data-generator
  labels:
    app: prometheus-data-generator
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: metrics
  selector:
    app: prometheus-data-generator
